# Generated by Django 4.1.1 on 2022-10-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default-product-image.jpg', upload_to='', verbose_name='Изображение'),
        ),
    ]
